package com.example.demo.dto.entity;

import java.util.Date;

public class Account {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.user_id
     *
     * @mbg.generated Mon Nov 04 10:26:16 JST 2024
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.user_role
     *
     * @mbg.generated Mon Nov 04 10:26:16 JST 2024
     */
    private String userRole;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.last_login
     *
     * @mbg.generated Mon Nov 04 10:26:16 JST 2024
     */
    private Date lastLogin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.created_at
     *
     * @mbg.generated Mon Nov 04 10:26:16 JST 2024
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.create_user
     *
     * @mbg.generated Mon Nov 04 10:26:16 JST 2024
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.updated_at
     *
     * @mbg.generated Mon Nov 04 10:26:16 JST 2024
     */
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.update_user
     *
     * @mbg.generated Mon Nov 04 10:26:16 JST 2024
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.delete_flg
     *
     * @mbg.generated Mon Nov 04 10:26:16 JST 2024
     */
    private Short deleteFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.deleted_at
     *
     * @mbg.generated Mon Nov 04 10:26:16 JST 2024
     */
    private Date deletedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.delete_user
     *
     * @mbg.generated Mon Nov 04 10:26:16 JST 2024
     */
    private String deleteUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.user_id
     *
     * @return the value of account.user_id
     *
     * @mbg.generated Mon Nov 04 10:26:16 JST 2024
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.user_id
     *
     * @param userId the value for account.user_id
     *
     * @mbg.generated Mon Nov 04 10:26:16 JST 2024
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.user_role
     *
     * @return the value of account.user_role
     *
     * @mbg.generated Mon Nov 04 10:26:16 JST 2024
     */
    public String getUserRole() {
        return userRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.user_role
     *
     * @param userRole the value for account.user_role
     *
     * @mbg.generated Mon Nov 04 10:26:16 JST 2024
     */
    public void setUserRole(String userRole) {
        this.userRole = userRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.last_login
     *
     * @return the value of account.last_login
     *
     * @mbg.generated Mon Nov 04 10:26:16 JST 2024
     */
    public Date getLastLogin() {
        return lastLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.last_login
     *
     * @param lastLogin the value for account.last_login
     *
     * @mbg.generated Mon Nov 04 10:26:16 JST 2024
     */
    public void setLastLogin(Date lastLogin) {
        this.lastLogin = lastLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.created_at
     *
     * @return the value of account.created_at
     *
     * @mbg.generated Mon Nov 04 10:26:16 JST 2024
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.created_at
     *
     * @param createdAt the value for account.created_at
     *
     * @mbg.generated Mon Nov 04 10:26:16 JST 2024
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.create_user
     *
     * @return the value of account.create_user
     *
     * @mbg.generated Mon Nov 04 10:26:16 JST 2024
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.create_user
     *
     * @param createUser the value for account.create_user
     *
     * @mbg.generated Mon Nov 04 10:26:16 JST 2024
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.updated_at
     *
     * @return the value of account.updated_at
     *
     * @mbg.generated Mon Nov 04 10:26:16 JST 2024
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.updated_at
     *
     * @param updatedAt the value for account.updated_at
     *
     * @mbg.generated Mon Nov 04 10:26:16 JST 2024
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.update_user
     *
     * @return the value of account.update_user
     *
     * @mbg.generated Mon Nov 04 10:26:16 JST 2024
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.update_user
     *
     * @param updateUser the value for account.update_user
     *
     * @mbg.generated Mon Nov 04 10:26:16 JST 2024
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.delete_flg
     *
     * @return the value of account.delete_flg
     *
     * @mbg.generated Mon Nov 04 10:26:16 JST 2024
     */
    public Short getDeleteFlg() {
        return deleteFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.delete_flg
     *
     * @param deleteFlg the value for account.delete_flg
     *
     * @mbg.generated Mon Nov 04 10:26:16 JST 2024
     */
    public void setDeleteFlg(Short deleteFlg) {
        this.deleteFlg = deleteFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.deleted_at
     *
     * @return the value of account.deleted_at
     *
     * @mbg.generated Mon Nov 04 10:26:16 JST 2024
     */
    public Date getDeletedAt() {
        return deletedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.deleted_at
     *
     * @param deletedAt the value for account.deleted_at
     *
     * @mbg.generated Mon Nov 04 10:26:16 JST 2024
     */
    public void setDeletedAt(Date deletedAt) {
        this.deletedAt = deletedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.delete_user
     *
     * @return the value of account.delete_user
     *
     * @mbg.generated Mon Nov 04 10:26:16 JST 2024
     */
    public String getDeleteUser() {
        return deleteUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.delete_user
     *
     * @param deleteUser the value for account.delete_user
     *
     * @mbg.generated Mon Nov 04 10:26:16 JST 2024
     */
    public void setDeleteUser(String deleteUser) {
        this.deleteUser = deleteUser;
    }
}