package com.example.demo.dto.entity;

import java.util.Date;

public class Item {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.id
     *
     * @mbg.generated Sat Nov 02 18:16:29 JST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.item_name
     *
     * @mbg.generated Sat Nov 02 18:16:29 JST 2024
     */
    private String itemName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.price
     *
     * @mbg.generated Sat Nov 02 18:16:29 JST 2024
     */
    private Integer price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.item_description1
     *
     * @mbg.generated Sat Nov 02 18:16:29 JST 2024
     */
    private String itemDescription1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.item_description2
     *
     * @mbg.generated Sat Nov 02 18:16:29 JST 2024
     */
    private String itemDescription2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.item_description3
     *
     * @mbg.generated Sat Nov 02 18:16:29 JST 2024
     */
    private String itemDescription3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.created_at
     *
     * @mbg.generated Sat Nov 02 18:16:29 JST 2024
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.create_user
     *
     * @mbg.generated Sat Nov 02 18:16:29 JST 2024
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.updated_at
     *
     * @mbg.generated Sat Nov 02 18:16:29 JST 2024
     */
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.update_user
     *
     * @mbg.generated Sat Nov 02 18:16:29 JST 2024
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.delete_flg
     *
     * @mbg.generated Sat Nov 02 18:16:29 JST 2024
     */
    private Short deleteFlg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.deleted_at
     *
     * @mbg.generated Sat Nov 02 18:16:29 JST 2024
     */
    private Date deletedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.delete_user
     *
     * @mbg.generated Sat Nov 02 18:16:29 JST 2024
     */
    private String deleteUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.id
     *
     * @return the value of item.id
     *
     * @mbg.generated Sat Nov 02 18:16:29 JST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.id
     *
     * @param id the value for item.id
     *
     * @mbg.generated Sat Nov 02 18:16:29 JST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.item_name
     *
     * @return the value of item.item_name
     *
     * @mbg.generated Sat Nov 02 18:16:29 JST 2024
     */
    public String getItemName() {
        return itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.item_name
     *
     * @param itemName the value for item.item_name
     *
     * @mbg.generated Sat Nov 02 18:16:29 JST 2024
     */
    public void setItemName(String itemName) {
        this.itemName = itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.price
     *
     * @return the value of item.price
     *
     * @mbg.generated Sat Nov 02 18:16:29 JST 2024
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.price
     *
     * @param price the value for item.price
     *
     * @mbg.generated Sat Nov 02 18:16:29 JST 2024
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.item_description1
     *
     * @return the value of item.item_description1
     *
     * @mbg.generated Sat Nov 02 18:16:29 JST 2024
     */
    public String getItemDescription1() {
        return itemDescription1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.item_description1
     *
     * @param itemDescription1 the value for item.item_description1
     *
     * @mbg.generated Sat Nov 02 18:16:29 JST 2024
     */
    public void setItemDescription1(String itemDescription1) {
        this.itemDescription1 = itemDescription1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.item_description2
     *
     * @return the value of item.item_description2
     *
     * @mbg.generated Sat Nov 02 18:16:29 JST 2024
     */
    public String getItemDescription2() {
        return itemDescription2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.item_description2
     *
     * @param itemDescription2 the value for item.item_description2
     *
     * @mbg.generated Sat Nov 02 18:16:29 JST 2024
     */
    public void setItemDescription2(String itemDescription2) {
        this.itemDescription2 = itemDescription2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.item_description3
     *
     * @return the value of item.item_description3
     *
     * @mbg.generated Sat Nov 02 18:16:29 JST 2024
     */
    public String getItemDescription3() {
        return itemDescription3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.item_description3
     *
     * @param itemDescription3 the value for item.item_description3
     *
     * @mbg.generated Sat Nov 02 18:16:29 JST 2024
     */
    public void setItemDescription3(String itemDescription3) {
        this.itemDescription3 = itemDescription3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.created_at
     *
     * @return the value of item.created_at
     *
     * @mbg.generated Sat Nov 02 18:16:29 JST 2024
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.created_at
     *
     * @param createdAt the value for item.created_at
     *
     * @mbg.generated Sat Nov 02 18:16:29 JST 2024
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.create_user
     *
     * @return the value of item.create_user
     *
     * @mbg.generated Sat Nov 02 18:16:29 JST 2024
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.create_user
     *
     * @param createUser the value for item.create_user
     *
     * @mbg.generated Sat Nov 02 18:16:29 JST 2024
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.updated_at
     *
     * @return the value of item.updated_at
     *
     * @mbg.generated Sat Nov 02 18:16:29 JST 2024
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.updated_at
     *
     * @param updatedAt the value for item.updated_at
     *
     * @mbg.generated Sat Nov 02 18:16:29 JST 2024
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.update_user
     *
     * @return the value of item.update_user
     *
     * @mbg.generated Sat Nov 02 18:16:29 JST 2024
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.update_user
     *
     * @param updateUser the value for item.update_user
     *
     * @mbg.generated Sat Nov 02 18:16:29 JST 2024
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.delete_flg
     *
     * @return the value of item.delete_flg
     *
     * @mbg.generated Sat Nov 02 18:16:29 JST 2024
     */
    public Short getDeleteFlg() {
        return deleteFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.delete_flg
     *
     * @param deleteFlg the value for item.delete_flg
     *
     * @mbg.generated Sat Nov 02 18:16:29 JST 2024
     */
    public void setDeleteFlg(Short deleteFlg) {
        this.deleteFlg = deleteFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.deleted_at
     *
     * @return the value of item.deleted_at
     *
     * @mbg.generated Sat Nov 02 18:16:29 JST 2024
     */
    public Date getDeletedAt() {
        return deletedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.deleted_at
     *
     * @param deletedAt the value for item.deleted_at
     *
     * @mbg.generated Sat Nov 02 18:16:29 JST 2024
     */
    public void setDeletedAt(Date deletedAt) {
        this.deletedAt = deletedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.delete_user
     *
     * @return the value of item.delete_user
     *
     * @mbg.generated Sat Nov 02 18:16:29 JST 2024
     */
    public String getDeleteUser() {
        return deleteUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.delete_user
     *
     * @param deleteUser the value for item.delete_user
     *
     * @mbg.generated Sat Nov 02 18:16:29 JST 2024
     */
    public void setDeleteUser(String deleteUser) {
        this.deleteUser = deleteUser;
    }
}